name: Event-coordinator
on: [push]

env:
  GCP_REGISTRY: eu.gcr.io
  GCP_PROJECT: staffzo-316512
  GITHUB_SHA: ${{ github.sha }}
  GCP_REGION: europe-west1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: 'latest'
        service_account_key: ${{ secrets.CI_CD }}
        # service_account_key: ${{ secrets.API_GW_API_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
        gcloud config set run/platform managed
        gcloud config set run/region $GCP_REGION
        gcloud config set project $GCP_PROJECT
    
    - name: Build the Docker image frontend
      run: docker build . -t eu.gcr.io/$GCP_PROJECT/event-coordinator

    - name: Push image
      run: docker push eu.gcr.io/$GCP_PROJECT/event-coordinator

    - name: Cloud Run deploy
      run: |
        gcloud run deploy event-coordinator --image=eu.gcr.io/$GCP_PROJECT/event-coordinator --project=$GCP_PROJECT --memory=256Mi --concurrency=20 --max-instances=default --cpu=300m --min-instances=1 --platform=gke --cluster=projects/$GCP_PROJECT/zones/europe-west1/clusters/staffzo --cluster-location=europe-west1 --connectivity=internal --no-use-http2 --namespace=event-coordinator