name: Event-coordinator
on: [push]

env:
  GCP_REGISTRY: eu.gcr.io
  GCP_PROJECT: staffzo-316512
  GITHUB_SHA: ${{ github.sha }}
  GCP_REGION: europe-west1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: $GCP_PROJECT
        service_account_key: ${{ secrets.CI_CD }}
        export_default_credentials: true

    # Configure docker to use the gcloud command-line tool as a credential helper
    - name: Auth Docker
      run: gcloud --quiet auth configure-docker
    
    - name: Build the Docker image
      run: docker build . -t eu.gcr.io/$GCP_PROJECT/event-coordinator

    - name: Push image
      run: docker push eu.gcr.io/$GCP_PROJECT/event-coordinator

    - name: Cloud Run deploy
      run: |
        gcloud run deploy event-coordinator --image=eu.gcr.io/$GCP_PROJECT/event-coordinator --project=$GCP_PROJECT --memory=256Mi --concurrency=20 --max-instances=default --cpu=300m --min-instances=1 --platform=gke --cluster=projects/$GCP_PROJECT/zones/europe-west1-c/clusters/staffzo --cluster-location=europe-west1-c --connectivity=internal --no-use-http2 --namespace=event-coordinator --service-account=event-coordinator-sa@staffzo-316512.iam.gserviceaccount.com
